spring.application.name=pahamin
logging.level.org.springframework.security=TRACE
# Database
spring.datasource.url=jdbc:postgresql://acela.proxy.rlwy.net:13039/railway?sslmode=require&connectTimeout=30&socketTimeout=30
spring.datasource.username=postgres
spring.datasource.password=opqKxJhWZcodFnUEKPHHWpklXUIrUnQg
spring.datasource.driver-class-name=org.postgresql.Driver

#debugging
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# nanti diganti ke update untuk ddl-auto nya, tapi untuk sekarang biar cepet buat testingnya jadi create aja

# JWT
jwt.secret=pahamin-super-secret-key-untuk-jwt-auth-minimal-256bits-oke
jwt.expiration=86400000